"""Replace follows with connections

Revision ID: ae8fcb7881c7
Revises: 0554a209c7a0
Create Date: 2025-12-02 18:34:30.740819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae8fcb7881c7'
down_revision: Union[str, Sequence[str], None] = '0554a209c7a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requester_id', 'recipient_id', name='unique_connection')
    )
    op.create_index('idx_recipient', 'connections', ['recipient_id'], unique=False)
    op.create_index('idx_requester', 'connections', ['requester_id'], unique=False)
    op.create_index('idx_status', 'connections', ['status'], unique=False)
    op.create_index(op.f('ix_connections_id'), 'connections', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_connections_id'), table_name='connections')
    op.drop_index('idx_status', table_name='connections')
    op.drop_index('idx_requester', table_name='connections')
    op.drop_index('idx_recipient', table_name='connections')
    op.drop_table('connections')
    # ### end Alembic commands ###
