"""add follow indexes

Revision ID: cefd6d801857
Revises: 0bc1c6bfc2c9
Create Date: 2025-12-02 00:08:09.235574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cefd6d801857'
down_revision: Union[str, Sequence[str], None] = '0bc1c6bfc2c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_follows_followee_id', 'follows', ['followee_id'], unique=False)
    op.create_index('ix_follows_follower_id', 'follows', ['follower_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_follows_follower_id', table_name='follows')
    op.drop_index('ix_follows_followee_id', table_name='follows')
    # ### end Alembic commands ###
