"""Add tag system tables

Revision ID: e734d765d3ad
Revises: ae8fcb7881c7
Create Date: 2025-12-02 22:57:33.532950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e734d765d3ad'
down_revision: Union[str, Sequence[str], None] = 'ae8fcb7881c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=24), nullable=False),
    sa.Column('color_scheme', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='unique_user_tag')
    )
    op.create_index('idx_user_tags', 'tags', ['user_id'], unique=False)
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_table('connection_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connection_id', 'tag_id', name='unique_connection_tag')
    )
    op.create_index(op.f('ix_connection_tags_id'), 'connection_tags', ['id'], unique=False)
    op.create_table('post_audience_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_audience_tags_id'), 'post_audience_tags', ['id'], unique=False)
    op.add_column('posts', sa.Column('audience_type', sa.String(length=20), nullable=True))
    op.drop_constraint(op.f('posts_author_id_fkey'), 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'users', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key(op.f('posts_author_id_fkey'), 'posts', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    op.drop_column('posts', 'audience_type')
    op.drop_index(op.f('ix_post_audience_tags_id'), table_name='post_audience_tags')
    op.drop_table('post_audience_tags')
    op.drop_index(op.f('ix_connection_tags_id'), table_name='connection_tags')
    op.drop_table('connection_tags')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_index('idx_user_tags', table_name='tags')
    op.drop_table('tags')
    # ### end Alembic commands ###
