"""
Weekly Summary Generation for Digest Feature

This module generates weekly highlight summaries based on post importance scores.
The actual digest summaries for individual posts are generated by the ai_service microservice.

Important: This module is designed to be calm, non-judgmental, and factual.
It should never rank, compare, or create urgency.
"""
import logging

logger = logging.getLogger(__name__)


def generate_weekly_summary(posts_with_scores: list[dict]) -> str:
    """
    Generate a weekly highlight summary based on posts and their importance scores.
    
    Args:
        posts_with_scores: List of dicts with 'importance_score' and optionally 'summary'
    
    Returns:
        str: Gentle, pattern-based observation (e.g., "It was a quieter week overall.")
        None: If no posts provided (omit summary for empty weeks)
    
    Rules:
        - Pattern-based, not event-based
        - No scores, labels, or names highlighted
        - Short and gentle
        - May be omitted if week is very quiet
    """
    if not posts_with_scores:
        return None  # Omit summary for empty weeks
    
    avg_importance = sum(p.get('importance_score', 5.0) for p in posts_with_scores) / len(posts_with_scores)
    
    # Pattern-based summary based on average importance
    if avg_importance > 6:
        return "It was an eventful week. Several significant moments stood out among your connections."
    elif avg_importance > 4:
        return "A balanced week. Your friends and family shared a mix of daily routines and small joys."
    else:
        return "It was a quieter week overall. The focus seemed to be on rest, reflection, and small, peaceful moments."

